#!/usr/bin/env bash
# SPDX-FileCopyrightText: Cadasto B.V.
# SPDX-License-Identifier: BUSL-1.1
# Render the two EHDS pages FROM website/book/ehds.yaml.
#
# A readiness page typed by hand is wrong the first time a requirement's
# status changes, and wrong in the direction that matters: a stale "shipped"
# beside a requirement nothing implements is a false compliance claim on a
# public site. So the status lives in one committed file, both pages are a
# pure function of it, and the `ehds-pages` CI job re-renders and diffs.
#
# DETERMINISM. No clock, no HEAD commit, no network: two runs over an
# unchanged YAML produce identical bytes. The date a reader sees is the
# `regulation.read_on` field, which is when a human last read the regulation
# — a fact about the reading, not about the run.
#
# The legal text is NEVER restated as if it were binding. The YAML's
# `summary` fields are this project's paraphrase, the pages say so, and every
# page links the published regulation as the authority.
#
# Usage:
#   scripts/render/ehds-pages.sh            write both pages
#   scripts/render/ehds-pages.sh --check    fail when a committed page is stale
set -euo pipefail
cd "$(dirname "$0")/../.."

SRC="website/book/ehds.yaml"
READINESS="website/book/src/compliance/ehds-readiness.md"
TECHDOC="website/book/src/compliance/technical-documentation.md"
# The coverage matrix is injected into a HAND-WRITTEN page between markers,
# rather than owning a page of its own: the FHIR chapter is the place a reader
# already asks this question, and only the table is generated.
FHIR_PAGE="website/book/src/beyond-core/fhir.md"
FHIR_BEGIN="<!-- BEGIN generated: ehds-priority-categories -->"
FHIR_END="<!-- END generated: ehds-priority-categories -->"
SCRIPT="scripts/render/ehds-pages.sh"

CHECK=0
[[ "${1:-}" == "--check" ]] && CHECK=1

die() { printf 'ehds-pages: %s\n' "$1" >&2; exit 1; }

command -v yq >/dev/null || die "yq is not on PATH (mikefarah/yq v4)"
command -v jq >/dev/null || die "jq is not on PATH"
[[ -f "$SRC" ]] || die "$SRC does not exist"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

yq -o=json '.' "$SRC" > "$WORK/ehds.json" || die "$SRC is not valid YAML"

# Every status in the file must be one the vocabulary defines, or a typo
# becomes a silent blank cell on a compliance page.
bad="$(jq -r '
  [ (.requirements[].items[] | .status),
    (.components[] | .status) ]
  | map(select(. as $s | ["shipped","partial","planned","open"] | index($s) | not))
  | unique | join(", ")' "$WORK/ehds.json")"
[[ -z "$bad" ]] || die "unknown status value(s): $bad (expected shipped, partial, planned or open)"
bad="$(jq -r '
  [ .technical_documentation[].points[].source ]
  | map(select(. as $s | ["shipped","partial","open"] | index($s) | not))
  | unique | join(", ")' "$WORK/ehds.json")"
[[ -z "$bad" ]] || die "unknown source value(s): $bad (expected shipped, partial or open)"
# Each Annex III element names the file of the documentation tree that holds
# it, and the page links that file, so a missing file is a dead link on a
# compliance page and stops the render.
while IFS= read -r tree; do
  [[ -n "$tree" && "$tree" != "null" ]] || die "an Annex III element names no tree file"
  [[ -f "docs/technical-documentation/$tree" ]] || die "docs/technical-documentation/$tree does not exist"
done < <(jq -r '.technical_documentation[].tree' "$WORK/ehds.json")

reg_title="$(jq -r '.regulation.title' "$WORK/ehds.json")"
reg_url="$(jq -r '.regulation.url' "$WORK/ehds.json")"
reg_journal="$(jq -r '.regulation.journal' "$WORK/ehds.json")"
read_on="$(jq -r '.regulation.read_on' "$WORK/ehds.json")"

render_readiness() {
  cat <<HEADER
<!-- Generated by $SCRIPT from website/book/ehds.yaml. Do not edit by hand:
     the CI job re-renders and diffs, so an edit here is reverted with a red
     build. Change the YAML. -->

# EHDS readiness

The European Health Data Space regulation puts obligations on EHR systems in
its Chapter III: an EHR system must include two harmonised software
components, meet the essential requirements of Annex II, and carry technical
documentation and an EU declaration of conformity before it is placed on the
market or put into service.

Cadasto B.V. is the manufacturer of each tagged FerroEHR release, and the EHR
system it declares is FerroEHR and FerroBRIDGE together: FerroEHR ships the
European logging software component, FerroBRIDGE the European
interoperability software component. This page states, requirement by
requirement, what FerroEHR provides today, and names FerroBRIDGE where a
requirement is its part.

<!-- toc -->

> [!WARNING]
> **No conformity assessment has been carried out.** The technical
> documentation of Article 37 is being drawn up and still lacks elements (see
> [Technical documentation](technical-documentation.md)), no EU declaration
> of conformity exists under Article 39, and FerroEHR is not registered under
> Article 49. A status of "Shipped" below means the software provides the
> capability. It is not a claim of conformity, and nothing on this page is
> one.

## The regulation, and how to check this page against it

[$reg_title]($reg_url), $reg_journal.

Every requirement identifier, heading and date on this page was read from the
Official Journal text vendored in the repository at
[\`docs/law/eu/ehds/text.html\`](https://github.com/FerroHEALTH/FerroEHR/blob/main/docs/law/eu/ehds/text.html)
on **$read_on**. The wording in the "Requirement" column is this project's own
paraphrase for navigation; the regulation is the authority and its text
governs. Where the two differ, the regulation is right and this page is a
defect worth reporting.

## When it applies

HEADER

  jq -r '.dates[] | "- **\(.when):** \(.what)"' "$WORK/ehds.json"

  cat <<'COMPONENTS'

The last of those reaches a deployment that a health institution runs for
itself, or that is offered as a service: Article 26(2) treats both as *put
into service*. An organisation that runs an unmodified FerroEHR release for
itself puts Cadasto B.V.'s product into service and does not become the
manufacturer. Where Cadasto B.V. hosts FerroEHR as a service for a customer,
it is the manufacturer and the operator of that deployment.

## The two harmonised software components

Article 25(1) requires an EHR system to include both. Each is shipped by one
product of the EHR system Cadasto B.V. declares.

| Component | Status | Where it stands |
|---|---|---|
COMPONENTS

  jq -r '
    def badge: {shipped:"Shipped", partial:"Partial", planned:"Planned", open:"Open question"}[.];
    def issue_links: if (.issues // []) | length == 0 then "" else
      (" (" + ([.issues[] | "[#\(.)](https://github.com/FerroHEALTH/FerroEHR/issues/\(.))"] | join(", ")) + ")") end;
    .components[]
    | "| \(.name) | \(.status | badge)\(. | issue_links) | \(.note | gsub("\n"; " ")) |"
  ' "$WORK/ehds.json"

  cat <<'ANNEX2'

## Annex II: the essential requirements

The identifiers are the Annex's own. "Evidence" links what a reader can check
for themselves; "Gap" says what is missing when a row is not complete, and
the issue that closes it where one exists.

ANNEX2

  jq -r '
    def badge: {shipped:"Shipped", partial:"Partial", planned:"Planned", open:"Open question"}[.];
    def issue_links: if (.issues // []) | length == 0 then "" else
      ([.issues[] | "[#\(.)](https://github.com/FerroHEALTH/FerroEHR/issues/\(.))"] | join(", ")) end;
    def evidence: if (.evidence // []) | length == 0 then "—" else
      ([.evidence[] | "[\(.text)](\(.href))"] | join("; ")) end;
    def detail:
      [ (if .gap then "**Gap:** " + (.gap | gsub("\n"; " ")) else empty end),
        (if .question then "**Question:** " + (.question | gsub("\n"; " ")) else empty end),
        (if ((.issues // []) | length) > 0 then "Tracked in " + (. | issue_links) else empty end) ]
      | if length == 0 then "—" else join(" ") end;
    .requirements[]
    | ("### \(.group). \(.heading)\n",
       "| # | Requirement (our paraphrase) | Status | Evidence | Notes |",
       "|---|---|---|---|---|",
       (.items[] | "| \(.id) | \(.summary | gsub("\n"; " ")) | \(.status | badge) | \(. | evidence) | \(. | detail) |"),
       "")
  ' "$WORK/ehds.json"

  cat <<'DECISIONS'
## The position this page rests on

Cadasto B.V. decided these on 2026-10-06. They answer the questions earlier
versions of this page left open.

DECISIONS

  jq -r '
    def issue_links: if (.issues // []) | length == 0 then "" else
      (" ([#" + ([.issues[] | "\(.)](https://github.com/FerroHEALTH/FerroEHR/issues/\(.))"] | join(", [#")) + ")") end;
    .decisions[] | "- \(.text | gsub("\n"; " "))\(. | issue_links)"
  ' "$WORK/ehds.json"

  cat <<'COUNSEL'

## Questions for counsel

Nothing in this repository answers these. They are stated as questions until
counsel has answered them.

COUNSEL

  jq -r '
    def issue_links: if (.issues // []) | length == 0 then "" else
      (" Tracked in " + ([.issues[] | "[#\(.)](https://github.com/FerroHEALTH/FerroEHR/issues/\(.))"] | join(", ")) + ".") end;
    .counsel[] | "- \(.question | gsub("\n"; " "))\(. | issue_links)"
  ' "$WORK/ehds.json"

  cat <<'FOOTER'

## The Cyber Resilience Act

FerroEHR is also a product with digital elements under Regulation (EU)
2024/2847. Its reporting duties apply now, and from 11 December 2027 the CRA's
essential requirements are assessed through this Regulation's Chapter III
procedure, in one technical documentation set and one declaration. The
[Cyber Resilience Act](cra.md) page states the position.

## Related

- [Technical documentation](technical-documentation.md): the Annex III
  elements, and the file of the documentation tree that holds each.
- [Information sheet](information-sheet.md) and
  [instructions for use](instructions-for-use.md): what accompanies each
  release (Article 30(1)(d), Article 38).
- [Shared responsibility](shared-responsibility.md): which duties the
  software can carry and which belong to the deployment.
- [Control matrix](control-matrix.md): the legal controls the tracker
  declares, generated from the tracker.
FOOTER
}

render_techdoc() {
  cat <<HEADER
<!-- Generated by $SCRIPT from website/book/ehds.yaml. Do not edit by hand:
     the CI job re-renders and diffs, so an edit here is reverted with a red
     build. Change the YAML. -->

# Technical documentation

Article 37 of the EHDS regulation requires a manufacturer to draw up technical
documentation before an EHR system is placed on the market or put into
service, and to keep it up to date. Article 37(2) says it must contain at
least the elements of Annex III, and a reference to the results of the
European digital testing environment of Article 40. From 11 December 2027 the
same documentation carries the content of CRA Annex VII (CRA Art. 31(3) as
EHDS Article 104 replaces it).

Cadasto B.V., the manufacturer of each tagged FerroEHR release, keeps that
documentation in the repository, in
[\`docs/technical-documentation/\`](https://github.com/FerroHEALTH/FerroEHR/tree/main/docs/technical-documentation):
one file per Annex III element and per CRA Annex VII point that adds one, each
linking its evidence. The tree as it stands at a release tag is that release's
documentation. This page maps each Annex III element to its file and to the
published material it cites. It covers FerroEHR's part of the EHR system, the
logging component and the system-level requirements; FerroBRIDGE documents the
interoperability component.

<!-- toc -->

> [!WARNING]
> The documentation is incomplete: element 3 and element 6 cannot be written
> yet, and element 4 lacks the testing-environment results. No EU declaration
> of conformity exists. An "Available" row below means the material the
> element asks for is written and cited from the tree, not that any authority
> has examined it.

[$reg_title]($reg_url), $reg_journal. Read on **$read_on**; the regulation
governs and the summaries here are this project's paraphrase.

## Annex III, element by element

HEADER

  jq -r '
    def badge: {shipped:"Available", partial:"Partial", open:"Missing"}[.];
    def link: if .href then "[what exists](\(.href))" else "—" end;
    def note: if .note then (.note | gsub("\n"; " ")) else "—" end;
    def tree: "[`\(.tree)`](https://github.com/FerroHEALTH/FerroEHR/blob/main/docs/technical-documentation/\(.tree))";
    .technical_documentation[]
    | ("### \(.id). \(.heading)\n",
       "Documented in \(. | tree).\n",
       "| # | Element | State | Material | Notes |",
       "|---|---|---|---|---|",
       (.points[] | "| \(.id) | \(.summary | gsub("\n"; " ")) | \(.source | badge) | \(. | link) | \(. | note) |"),
       "")
  ' "$WORK/ehds.json"

  cat <<'REST'
## What CRA Annex VII adds

CRA Annex VII asks for four things Annex III does not, each with its own file
in the tree: the design, development and vulnerability-handling processes
with the software bills of materials (point 2), the cybersecurity
[risk assessment](cra-risk-assessment.md) (point 3), the information taken
into account to set the support period (point 4), and the standards applied or
the solutions adopted in their place (point 5). The
[hazard log](hazard-log.md) is the EHDS-side assessment of the logging
component, which CRA Art. 13(4), as EHDS Article 104 amends it, lets the
cybersecurity risk assessment be part of.

## Test evidence

Element 4 asks for the results of the verification and validation tests. What
exists is the openEHR conformance record (an independent instrument's runs
against a composed deployment, with the results, verdicts and the statement
committed under `docs/conformance/` and published on the
[conformance pages](../conformance.md)) and the tests the hazard log names for
each control of the logging component.

The conformance record demonstrates conformity to the **openEHR**
specifications. Conformity to Annex II is a different claim against a
different yardstick. The European digital testing environment of Article 40,
whose results Article 37(2) asks the documentation to reference, is not
published; running it is tracked in
[#3620](https://github.com/FerroHEALTH/FerroEHR/issues/3620).

## Declaration of conformity

Article 39 requires an EU declaration of conformity stating that the
essential requirements of Annex II are met, and Annex IV sets out what it
contains, including the common specifications applied and the result of the
Article 40 testing environment. **No declaration has been drawn up.** The
common specifications of Article 36 have not been adopted, the testing
environment is not published, and the exchange format the interoperability
component must carry waits on implementing acts under Article 15(1). Chapter
III applies to EHR systems from 26 March 2029 (Article 105).

When a declaration is drawn up, Cadasto B.V. draws it up for the EHR system,
FerroEHR and FerroBRIDGE together, as one declaration for the EHDS and the
CRA. It is published online for each release it covers, for at least ten
years (Article 39(4)), and kept with the documentation for ten years after the
system covered is placed on the market (Article 30(3)).

## Keeping it current, keeping it for ten years

- **Change control (Article 30(2)).** A release whose changes touch a module
  of the logging component updates the documentation tree in the same
  release, and the release procedure refuses the release otherwise.
- **Retention (Article 30(3)).** The tree is part of the signed release tag,
  which cannot be deleted or moved, and of the source archive each release
  deposits with Zenodo; the book pages it cites are frozen with each release at
  `/docs/vX.Y.Z/`.
- **Translation (Article 37(3) and (4)).** The documentation is written in
  English. A market surveillance authority that asks, with reasons, for a
  translation of parts of it into an official language of its Member State
  writes to info@cadasto.com, and Cadasto B.V. provides the translation within
  30 days of the request, or sooner where a serious and immediate risk
  justifies it.

## Related

- [EHDS readiness](ehds-readiness.md): the status per Annex II requirement.
- [Cyber Resilience Act](cra.md): the CRA position.
- [Shared responsibility](shared-responsibility.md): which duties belong to
  the deployment.
REST
}

render_categories() {
  cat <<'INTRO'
The six priority categories of personal electronic health data are Annex I of
the EHDS regulation, and Annex II 2.1 to 2.3 require an EHR system to provide
and receive them in the European electronic health record exchange format.
That format is set by implementing acts under Article 15(1) that have not
been adopted, so this table is not a conformance claim against it. What it says is
narrower and checkable: which category has a committed template whose example
composition round-trips through this façade today.

| Annex I | Category | Committed template | A profile mapping would target | Transform proven |
|---|---|---|---|---|
INTRO

  jq -r '
    def state: {template:"Yes", "no-template":"**No committed template**"}[.];
    .priority_categories[]
    | "| \(.id) | \(.name) | \(if .template == "" then "—" else "`corpus/templates/ckm/\(.template).opt`" end) | \(.fhir) | \(.state | state) |"
  ' "$WORK/ehds.json"

  cat <<'OUTRO'

"Transform proven" means exactly what the test asserts, and no more
(`app/ferroehr/tests/it/fhir_priority_categories.rs`): the category's
committed operational template builds a Web Template, its committed example
composition flattens against that template to a non-empty map, and a mapping
entry over a leaf taken from that map drives the reverse transform to a FHIR
resource carrying the composition's own value. The leaf is derived from the
map rather than written into the test, so a corpus refresh moves it and the
case still holds.

Three things it deliberately does **not** establish, each of which a reader
could otherwise assume:

- **No profile mapping ships.** The rightmost column says what a mapping for
  that category *would* target, not what exists. The test maps its leaf onto
  `Observation.note.text`, a free-text element: it proves the machinery
  carries real clinical content, not that an IPS-shaped `Bundle` or a
  `MedicationRequest` has been authored and reviewed. Mappings are data a
  deployment registers, as the section above describes.
- **It exercises the transform, not the endpoint.** The test calls the
  reverse transform directly, so routing, authorization and the stored-mapping
  lookup are covered by other tests rather than by this table.
- **It is not conformance to the exchange format**, which does not exist yet.

The connector this table measures is planned to leave: FerroBRIDGE
(<https://github.com/rubentalstra/FerroBRIDGE>) is the FHIRconnect and OMOP
bridge, and it ships the European interoperability software component of the
EHR system Cadasto B.V. declares, FerroEHR and FerroBRIDGE together.
[#3080](https://github.com/FerroHEALTH/FerroEHR/issues/3080) retires the
in-tree connector once FerroBRIDGE carries the mappings. The EHDS question does
not leave with the connector, because it is asked of the EHR system, so this
table moves to the compliance chapter at that point instead of being deleted
with the page it currently sits on.

Two of the example compositions this rests on — the patient summary and the
imaging report — were patched by hand rather than regenerated against a
running server, which their pack's provenance records and
[#1724](https://github.com/FerroHEALTH/FerroEHR/issues/1724) tracks. They are
real CKM templates either way; the caveat belongs beside a claim that leans on
them.
OUTRO
}

emit() {
  local target="$1" body="$2"
  if [[ "$CHECK" -eq 1 ]]; then
    [[ -f "$target" ]] || die "$target does not exist — run $SCRIPT"
    if ! diff -u "$target" "$body" > "$WORK/diff"; then
      cat "$WORK/diff" >&2
      die "$target is stale against $SRC — run $SCRIPT and commit the result"
    fi
  else
    mkdir -p "$(dirname "$target")"
    cp "$body" "$target"
  fi
}

render_readiness > "$WORK/readiness.md"
render_techdoc  > "$WORK/techdoc.md"
emit "$READINESS" "$WORK/readiness.md"
emit "$TECHDOC"   "$WORK/techdoc.md"

# The FHIR chapter keeps its hand-written prose; only the region between the
# markers is ours. A missing marker is an error rather than a silent skip.
grep -qF "$FHIR_BEGIN" "$FHIR_PAGE" || die "$FHIR_PAGE has no $FHIR_BEGIN marker"
grep -qF "$FHIR_END" "$FHIR_PAGE" || die "$FHIR_PAGE has no $FHIR_END marker"
{
  sed -n "1,/$(printf '%s' "$FHIR_BEGIN" | sed 's/[][\/.*^$]/\\&/g')/p" "$FHIR_PAGE"
  echo
  render_categories
  echo
  sed -n "/$(printf '%s' "$FHIR_END" | sed 's/[][\/.*^$]/\\&/g')/,\$p" "$FHIR_PAGE"
} > "$WORK/fhir.md"
emit "$FHIR_PAGE" "$WORK/fhir.md"

count="$(jq '[.requirements[].items[]] | length' "$WORK/ehds.json")"
if [[ "$CHECK" -eq 1 ]]; then
  echo "ehds-pages: both pages match $SRC ($count Annex II requirements)"
else
  echo "ehds-pages: wrote $READINESS and $TECHDOC ($count Annex II requirements)"
fi
