// @generated by openehr-codegen — DO NOT EDIT.
// SPDX-FileCopyrightText: Cadasto B.V.
// SPDX-FileCopyrightText: openEHR Foundation
// SPDX-License-Identifier: Apache-2.0

//! The openEHR spec package `v1_1/ehr_extract/generic_extract` — generated module tree.

pub mod generic_content_item;
